- name: install and run nginx
  hosts: web
  become: yes
  tasks:
  - name : install niginx
    ansible.builtin.package:
      name: nginx
      state: present
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes